// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMV4fy6DHC4h3GUNhbVQcI1R_3NFkhIds',
    appId: '1:624802997316:web:5d4ac3d37f6db0ab128811',
    messagingSenderId: '624802997316',
    projectId: 'reddit-clone-190c7',
    authDomain: 'reddit-clone-190c7.firebaseapp.com',
    storageBucket: 'reddit-clone-190c7.appspot.com',
    measurementId: 'G-L2XE4L2ZRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCQwpIrNTz-tov1F7Uylf058ZwcSOn3_s',
    appId: '1:624802997316:android:4b51b4ed86acaf24128811',
    messagingSenderId: '624802997316',
    projectId: 'reddit-clone-190c7',
    storageBucket: 'reddit-clone-190c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbKvNMniIekvets_pYJEXa5ZN-01IiDWA',
    appId: '1:624802997316:ios:d74dee677f4681ca128811',
    messagingSenderId: '624802997316',
    projectId: 'reddit-clone-190c7',
    storageBucket: 'reddit-clone-190c7.appspot.com',
    iosBundleId: 'com.lowjunkie.redditClone',
  );
}
